import 'package:homework_19/moduls.dart/enums.dart';
import 'package:homework_19/moduls.dart/moduklcha.dart';
import 'package:homework_19/utils/app_iamges.dart';

List<LayotModul> products = [
  LayotModul(Category.computers,
      iamge: AppImages.imageNot1,
      subTitle: "USD 999",
      title: "Surface laptop 3"),
  LayotModul(Category.computers,
      iamge: AppImages.imageNot2, subTitle: "USD 899", title: "XPS laptop 13"),
  LayotModul(Category.computers,
      iamge: AppImages.imageNot3, subTitle: "USD 1399", title: "LG Gram 17"),
  LayotModul(Category.computers,
      iamge: AppImages.imageNot4,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.computers,
      iamge: AppImages.imageNot5, subTitle: "USD 1399", title: "LG Gram 17"),
  LayotModul(Category.computers,
      iamge: AppImages.imageNot6,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.smartphones,
      iamge: AppImages.imagePthone1,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.smartphones,
      iamge: AppImages.imagePthone2,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.smartphones,
      iamge: AppImages.imagePthone3,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.smartphones,
      iamge: AppImages.imagePthone4, subTitle: "USD 1299", title: "Samsung"),
  LayotModul(Category.smartphones,
      iamge: AppImages.imagePthone5,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.speakers,
      iamge: AppImages.imageSpeaker1,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.speakers,
      iamge: AppImages.imageSpeaker2,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.speakers,
      iamge: AppImages.imageSpeaker3,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.speakers,
      iamge: AppImages.imageSpeaker4,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
  LayotModul(Category.speakers,
      iamge: AppImages.imageSpeaker5,
      subTitle: "USD 1299",
      title: "Macbook pro 13"),
];
